### ISSUE TITLE
SProducer is the wrong type

### ISSUE THREAD

**Issue by ivan-m** [zadarnowski/quiver#4]
For compatibility with `spconsume`, etc. `SProducer` should be defined in terms of `Producer` rather than `SP` (and thus have `forall a. P a ...` rather than `P () ...`).

**Comment by ivan-m** [comment]
(This also means that any time a function expects a `Producer`, providing it with an `SProducer` currently doesn't work.)

**Comment by zadarnowski** [comment]
Agree. Fixed.
