### ISSUE TITLE
spfoldr is wrong

### ISSUE THREAD

**Issue by ivan-m** [zadarnowski/quiver#5]
``` haskell
λ> sprun (spevery [1..10] >->> spfoldr (:) [] >&> snd)
[10,9,8,7,6,5,4,3,2,1]
λ> sprun (spevery [1..10] >->> spfoldl (flip (:)) [] >&> snd)
[10,9,8,7,6,5,4,3,2,1]
```

I would expect `spfoldr` to return results in order, but in fact it returns them in reverse order (due to the usage of `flip` in its definition; it's actually identical to `spfoldl`!).

**Comment by ivan-m** [comment]
This definition seems to work, but I'm not sure how efficient it is:

``` haskell
spfoldr :: (Functor f) => (a -> b -> b) -> b -> SQ a x f b
spfoldr f b = loop
  where
    loop = spconsume (\a -> f a <$> loop) (deliver b)
```

**Comment by zadarnowski** [comment]
Well spotted. Fixed.
