### ISSUE TITLE
Instances for the exceptions library

### ISSUE THREAD

**Issue by ivan-m** [zadarnowski/quiver#7]
I've currently implemented them [here](https://github.com/ivan-m/quiver-instances), but they should probably be part of Quiver proper (you can now do `bracket`, etc. inside of a quiver!)

**Comment by zadarnowski** [comment]
Sigh, alas, these instances don't work for asynchronous exceptions and exceptions raised in pure code, and therefore can't be used to reliably bracket resource allocation!

**Comment by ivan-m** [comment]
Yes, I've just discovered that myself and spent most of the afternoon trying to work out how to cope with it :(

**Comment by christian-marie** [comment]
Lol noobs!1

**Comment by ivan-m** [comment]
@christian-marie what pray tell is the solution O non-noobishness? ;-)

(For the record, I ended up using ResourceT for this.)

**Comment by christian-marie** [comment]
It was, unfortunately, sarcasm.

You two are a few of the most experienced and intelligent Haskellers that I know, and you both burned a good few days on the same problem. I don't see a solution to the underlying problem: exceptions are subtle and difficult, resourceT is the best answer now, I think.
